### Config connexion réseau (id / pass)
ansible_user: admin
ansible_ssh_pass: C1sco12345

### Network config for ansible
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: true
ansible_become_method: enable