- hosts: all
  gather_facts: false
  vars:
    template_user: Alex
    template_pass: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits',], length=15) }}"
  tasks:
    - name: include password file
      ansible.builtin.include_vars: password.yml

    - name: template mail
      template:
        src: template.j2
        dest: mail.txt