---
# tasks file for mysql
- name: Install MySQL-server on remote server
  ansible.builtin.package:
    name: mysql-server
    state: latest
  register: install_status
    
- name: Display install status
  ansible.builtin.debug:
    msg: "{{ install_status }}"
  when: install_status is defined

- name: Display message if installation success
  ansible.builtin.debug:
    msg: "{{ message }}"
  when: 
    - message is defined
    - install_status.failed == false

- name: Create documentation
  ansible.builtin.template:
    src: templates/documentation.j2
    dest: "/tmp/documentation-{{ inventory_hostname }}.md"
  become: false
  delegate_to: localhost
  when: install_status.failed == false